# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Your Name
email: your.email@example.com
description: >
  Personal website of Ananya Jain - Student, Researcher, and Developer
baseurl: ""
url: ""

# Social media profiles - Fill these in with your info
github_username: ananyamjain
linkedin_username: https://www.linkedin.com/in/ananya-jain-640599213/
scholar_username: # Optional - Google Scholar profile

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  
# Navigation
navigation:
  - title: About
    url: /
  - title: Experience
    url: /experience/
  - title: Projects
    url: /projects/
  - title: Publications
    url: /publications/

# Other settings
future: true
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 5  # Number of posts per page
paginate_path: "/blog/page:num/"  # URL structure for paginated pages

