steps:
  # ... other steps ...
  - name: Setup Ruby
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: '3.1' # or whatever version you're using
      bundler-cache: true # runs bundle install and caches gems automatically
  
  - name: Build site
    run: bundle exec jekyll build 